export const skills = [
  {
    id: 1,
    title: "Software Engineering",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: 1,
        title: "Front-end",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "HTML",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 2, title: "CSS", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 3,
            title: "JavaScript",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "React",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 5, title: "Vue", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 6,
            title: "Angular",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 7,
            title: "Svelte",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 8,
            title: "Next.js",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 9,
            title: "Nuxt.js",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 10,
            title: "Gatsby",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 11,
            title: "Wordpress",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 12,
            title: "Shopify",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 13,
            title: "WooCommerce",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 14,
            title: "Drupal",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 15,
            title: "Joomla",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 16,
            title: "Magento",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 17,
            title: "Prestashop",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 18,
            title: "Wix",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 19,
            title: "Wix",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 20,
            title: "Wix",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 2,
        title: "Back-end",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Node.js",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Python",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Java",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 4, title: "C#", createdAt: new Date(), updatedAt: new Date() },
          { id: 5, title: "PHP", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 6,
            title: "Ruby",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 7, title: "Go", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 8,
            title: "Rust",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 9,
            title: "Swift",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 10,
            title: "Kotlin",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 11,
            title: "TypeScript",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 12,
            title: "JavaScript",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 13,
            title: "C++",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 14, title: "C", createdAt: new Date(), updatedAt: new Date() },
          { id: 15, title: "R", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 16,
            title: "Perl",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 17,
            title: "Scala",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 18,
            title: "Groovy",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 19,
            title: "Clojure",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 20,
            title: "Elixir",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 3,
        title: "Full-stack",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Node.js",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Python",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Java",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 4, title: "C#", createdAt: new Date(), updatedAt: new Date() },
          { id: 5, title: "PHP", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 6,
            title: "Ruby",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 7, title: "Go", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 8,
            title: "Rust",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 9,
            title: "Swift",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 10,
            title: "Kotlin",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 11,
            title: "TypeScript",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 12,
            title: "JavaScript",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 13,
            title: "C++",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 14, title: "C", createdAt: new Date(), updatedAt: new Date() },
          { id: 15, title: "R", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 16,
            title: "Perl",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 17,
            title: "Scala",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 18,
            title: "Groovy",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 19,
            title: "Clojure",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 20,
            title: "Elixir",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 4,
        title: "Mobile",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Swift",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Kotlin",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 3, title: "C#", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 4,
            title: "Java",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 5,
            title: "Python",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 6, title: "C++", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 7,
            title: "React Native",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 8,
            title: "Flutter",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 5,
        title: "DevOps",
        createdAt: new Date(),
        updatedAt: new Date(),

        technologies: [
          {
            id: 1,
            title: "Docker",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Kubernetes",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Jenkins",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 4, title: "Git", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 5,
            title: "Jira",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 6,
            title: "Confluence",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 7,
            title: "Slack",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 8,
            title: "Trello",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 9,
            title: "Ansible",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 10,
            title: "Github Action",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 11,
            title: "Gitlab",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 12,
            title: "Terraform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 6,
        title: "Data Science",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Python",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          { id: 2, title: "R", createdAt: new Date(), updatedAt: new Date() },
          { id: 3, title: "SQL", createdAt: new Date(), updatedAt: new Date() },
          {
            id: 4,
            title: "Tableau",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 5,
            title: "Power BI",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 6,
            title: "Excel",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 7,
            title: "Jupyter",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 8,
            title: "Scikit-learn",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 9,
            title: "Pandas",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 10,
            title: "TensorFlow",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 11,
            title: "Numpy",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 12,
            title: "Matplotlib",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 7,
        title: "AI/ML",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Python",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Pytorch",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "TensorFlow",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Keras",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 5,
            title: "Scikit-learn",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 6,
            title: "OpenAi",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 7,
            title: "Jupyter",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 8,
            title: "HuggingFace",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 9,
            title: "Machine learning",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 10,
            title: "Deep learning",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 11,
            title: "Neural networks",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 12,
            title: "Reinforcement learning",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 13,
            title: "NLP",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 14,
            title: "Computer vision",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 8,
        title: "Database",
        createdAt: new Date(),
        updatedAt: new Date(),
        sousSkills: [
          {
            id: 1,
            title: "SQL",
            createdAt: new Date(),
            updatedAt: new Date(),
            technologies: [
              {
                id: 1,
                title: "MySQL",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 2,
                title: "PostgreSQL",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 3,
                title: "Oracle",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 4,
                title: "Microsoft SQL Server",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 5,
                title: "MariaDB",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 6,
                title: "SQLite",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 7,
                title: "Firestore",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 8,
                title: "Firebase",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 9,
                title: "SupaBase",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
            ],
          },
          {
            id: 2,
            title: "NoSQL",
            createdAt: new Date(),
            updatedAt: new Date(),
            technologies: [
              {
                id: 1,
                title: "MongoDB",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 2,
                title: "Couchbase",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 3,
                title: "Cassandra",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
            ],
          },
          {
            id: 3,
            title: "Caching",
            createdAt: new Date(),
            updatedAt: new Date(),
            technologies: [
              {
                id: 1,
                title: "Redis",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 2,
                title: "Memcached",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
            ],
          },
          {
            id: 4,
            title: "ORM",
            createdAt: new Date(),
            updatedAt: new Date(),
            technologies: [
              {
                id: 1,
                title: "Sequelize",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 2,
                title: "TypeORM",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 3,
                title: "Prisma",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 4,
                title: "Drizzle",
                createdAt: new Date(),
                updatedAt: new Date(),
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Cybersecurity",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: 1,
        title: "Pentesting",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Metasploit",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Nmap",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Snort",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "pfSense",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 5,
            title: "Nikto",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 6,
            title: "Hydra",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 2,
        title: "Network Security",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "WireShark",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Snort",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "pfSense",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Cisco ASA",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 3,
        title: "Cloud Security",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "AWS Security Hub",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Azure Security Center",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Prisma Cloud",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 4,
        title: "Cryptography",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "OpenSSl",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "GPG",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Hashicorp Vault",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 5,
        title: "Forensics",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Volatility",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Autopsy",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "EnCase",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "FTK",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 6,
        title: "Threat Intelligence",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "MISP",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "TheHive",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "OpenCTI",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Resilient",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "UI/UX Design",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: 1,
        title: "Wireframing",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Figma",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Adobe XD",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Sketch",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "InVision",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 2,
        title: "Prototyping",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Figma",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Adobe XD",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Sketch",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "InVision",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 3,
        title: "Visual Design",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Figma",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Illustrator",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Photoshop",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Canva",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 4,
        title: "User Research",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "User Research",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "User Testing",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Lookback",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Maze",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 5,
        title: "Interaction Design",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 4,
    title: "Cloud & Infrastructure",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: 1,
        title: "AWS",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "EC2",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "S3",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "RDS",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "VPC",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 5,
            title: "IAM",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 6,
            title: "Lambda",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 7,
            title: "API Gateway",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 8,
            title: "DynamoDB",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 9,
            title: "SNS",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 10,
            title: "SQS",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 11,
            title: "SNS",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 2,
        title: "Azure",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Azure DevOps",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "App service",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "AKS",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 3,
        title: "Google Cloud",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "GKE",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Big Query",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Firebase",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 4,
        title: "Kubernetes",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Helm",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Kubectl",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Prometheus",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Grafana",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 5,
        title: "CI/CD",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Github Action",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Jenkins",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Gitlab CI",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "CircleCI",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: "Business & Project Management",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: 1,
        title: "Agile/Scrum",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Jira",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Trello",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Azure DevOps",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 2,
        title: "Product Management",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Notion",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Monday.com",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Asana",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "ClickUp",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 3,
        title: "Project Planning",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "MS Project",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Monday.com",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 4,
        title: "Team Leadership",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Slack",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Zoom",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Miro",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 5,
        title: "Business Analysis",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Excel",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Tableau",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Power BI",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: 6,
    title: "Data & Analytics",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: 1,
        title: "Big Data",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Hadoop",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Spark",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Hive",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Kafka",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 2,
        title: "Data Engineering",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Airflow",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "DBT",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "SnowFlake",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 3,
        title: "Data Visualization",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Tableau",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Power BI",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "QlikView",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Looker",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 4,
        title: "Business Intelligence",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Qlik",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "Domo",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Metabase",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: 5,
        title: "Statistics",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: 1,
            title: "Matlab",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 2,
            title: "R",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 3,
            title: "Python",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 4,
            title: "Excel",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: 5,
            title: "Tableau",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
];
