// Architecture cohérente selon le schéma Prisma
// Skill -> sousSkill -> Technology

export const skills = [
  {
    id: "software-engineering",
    title: "Software Engineering",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "frontend",
        title: "Front-end",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "html",
            title: "HTML",
            icon: "🌐",
            color: "#E34F26",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "css",
            title: "CSS",
            icon: "🎨",
            color: "#1572B6",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "javascript",
            title: "JavaScript",
            icon: "⚡",
            color: "#F7DF1E",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "typescript",
            title: "TypeScript",
            icon: "📘",
            color: "#3178C6",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "react",
            title: "React",
            icon: "⚛️",
            color: "#61DAFB",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "vue",
            title: "Vue.js",
            icon: "💚",
            color: "#4FC08D",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "angular",
            title: "Angular",
            icon: "🅰️",
            color: "#DD0031",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "svelte",
            title: "Svelte",
            icon: "🔥",
            color: "#FF3E00",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "nextjs",
            title: "Next.js",
            icon: "▲",
            color: "#000000",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "nuxtjs",
            title: "Nuxt.js",
            icon: "💚",
            color: "#00DC82",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "gatsby",
            title: "Gatsby",
            icon: "🚀",
            color: "#663399",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "backend",
        title: "Back-end",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "nodejs",
            title: "Node.js",
            icon: "🟢",
            color: "#339933",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "python",
            title: "Python",
            icon: "🐍",
            color: "#3776AB",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "java",
            title: "Java",
            icon: "☕",
            color: "#ED8B00",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "csharp",
            title: "C#",
            icon: "#️⃣",
            color: "#239120",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "php",
            title: "PHP",
            icon: "🐘",
            color: "#777BB4",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "ruby",
            title: "Ruby",
            icon: "💎",
            color: "#CC342D",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "go",
            title: "Go",
            icon: "🐹",
            color: "#00ADD8",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "rust",
            title: "Rust",
            icon: "🦀",
            color: "#000000",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "mobile",
        title: "Mobile Development",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "swift",
            title: "Swift",
            icon: "🍎",
            color: "#FA7343",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "kotlin",
            title: "Kotlin",
            icon: "🤖",
            color: "#0095D5",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "react-native",
            title: "React Native",
            icon: "📱",
            color: "#61DAFB",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "flutter",
            title: "Flutter",
            icon: "🦋",
            color: "#02569B",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "devops",
        title: "DevOps & Infrastructure",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "docker",
            title: "Docker",
            icon: "🐳",
            color: "#2496ED",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "kubernetes",
            title: "Kubernetes",
            icon: "☸️",
            color: "#326CE5",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "jenkins",
            title: "Jenkins",
            icon: "🔧",
            color: "#D33833",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "git",
            title: "Git",
            icon: "📝",
            color: "#F05032",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "github-actions",
            title: "GitHub Actions",
            icon: "🚀",
            color: "#2088FF",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "terraform",
            title: "Terraform",
            icon: "🏗️",
            color: "#623CE4",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "ansible",
            title: "Ansible",
            icon: "🔴",
            color: "#EE0000",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "database",
    title: "Database & Storage",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "sql",
        title: "SQL Databases",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "mysql",
            title: "MySQL",
            icon: "🐬",
            color: "#4479A1",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "postgresql",
            title: "PostgreSQL",
            icon: "🐘",
            color: "#336791",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "sqlite",
            title: "SQLite",
            icon: "💾",
            color: "#003B57",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "oracle",
            title: "Oracle",
            icon: "🔴",
            color: "#F80000",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "nosql",
        title: "NoSQL Databases",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "mongodb",
            title: "MongoDB",
            icon: "🍃",
            color: "#47A248",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "redis",
            title: "Redis",
            icon: "🔴",
            color: "#DC382D",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "cassandra",
            title: "Cassandra",
            icon: "⚡",
            color: "#1287B1",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "orm",
        title: "ORM & Query Builders",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "prisma",
            title: "Prisma",
            icon: "🔷",
            color: "#2D3748",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "typeorm",
            title: "TypeORM",
            icon: "🏗️",
            color: "#E83524",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "sequelize",
            title: "Sequelize",
            icon: "📊",
            color: "#52B0E7",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "data-science",
    title: "Data Science & Analytics",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "analytics",
        title: "Data Analytics",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "pandas",
            title: "Pandas",
            icon: "🐼",
            color: "#150458",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "numpy",
            title: "NumPy",
            icon: "🔢",
            color: "#013243",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "r",
            title: "R",
            icon: "📈",
            color: "#276DC3",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "sql",
            title: "SQL",
            icon: "🗃️",
            color: "#336791",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "visualization",
        title: "Data Visualization",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "tableau",
            title: "Tableau",
            icon: "📊",
            color: "#E97627",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "powerbi",
            title: "Power BI",
            icon: "📈",
            color: "#F2C811",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "matplotlib",
            title: "Matplotlib",
            icon: "📉",
            color: "#11557C",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "ai-ml",
    title: "AI & Machine Learning",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "frameworks",
        title: "ML Frameworks",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "tensorflow",
            title: "TensorFlow",
            icon: "🧠",
            color: "#FF6F00",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "pytorch",
            title: "PyTorch",
            icon: "🔥",
            color: "#EE4C2C",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "scikit-learn",
            title: "Scikit-learn",
            icon: "🤖",
            color: "#F7931E",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "keras",
            title: "Keras",
            icon: "🧠",
            color: "#D00000",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "nlp",
        title: "Natural Language Processing",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "huggingface",
            title: "Hugging Face",
            icon: "🤗",
            color: "#FFD21E",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "openai",
            title: "OpenAI",
            icon: "🤖",
            color: "#412991",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "pentesting",
        title: "Penetration Testing",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "metasploit",
            title: "Metasploit",
            icon: "🎯",
            color: "#1976D2",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "nmap",
            title: "Nmap",
            icon: "🔍",
            color: "#4CAF50",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "wireshark",
            title: "Wireshark",
            icon: "🦈",
            color: "#1976D2",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "burp-suite",
            title: "Burp Suite",
            icon: "🔐",
            color: "#FF5722",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "network-security",
        title: "Network Security",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "snort",
            title: "Snort",
            icon: "🚨",
            color: "#E91E63",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "pfsense",
            title: "pfSense",
            icon: "🛡️",
            color: "#2196F3",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "cisco-asa",
            title: "Cisco ASA",
            icon: "🔒",
            color: "#1976D2",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "design",
    title: "UI/UX Design",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "design-tools",
        title: "Design Tools",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "figma",
            title: "Figma",
            icon: "🎨",
            color: "#F24E1E",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "adobe-xd",
            title: "Adobe XD",
            icon: "🔷",
            color: "#FF61F6",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "sketch",
            title: "Sketch",
            icon: "💎",
            color: "#F7B500",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "photoshop",
            title: "Photoshop",
            icon: "🖼️",
            color: "#31A8FF",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "illustrator",
            title: "Illustrator",
            icon: "✏️",
            color: "#FF9A00",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "prototyping",
        title: "Prototyping & Testing",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "invision",
            title: "InVision",
            icon: "🔗",
            color: "#FF3366",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "maze",
            title: "Maze",
            icon: "🧪",
            color: "#09CF83",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "principle",
            title: "Principle",
            icon: "⚡",
            color: "#5B57D9",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "cloud",
    title: "Cloud & Infrastructure",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "aws",
        title: "Amazon Web Services",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "ec2",
            title: "EC2",
            icon: "☁️",
            color: "#FF9900",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "s3",
            title: "S3",
            icon: "🪣",
            color: "#569A31",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "lambda",
            title: "Lambda",
            icon: "⚡",
            color: "#FF9900",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "rds",
            title: "RDS",
            icon: "🗄️",
            color: "#3F48CC",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "azure",
        title: "Microsoft Azure",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "azure-app-service",
            title: "App Service",
            icon: "🌐",
            color: "#0078D4",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "azure-functions",
            title: "Azure Functions",
            icon: "⚡",
            color: "#0078D4",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "gcp",
        title: "Google Cloud Platform",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "gce",
            title: "Compute Engine",
            icon: "⚙️",
            color: "#4285F4",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "cloud-functions",
            title: "Cloud Functions",
            icon: "⚡",
            color: "#4285F4",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
];
