// Architecture cohérente selon le schéma Prisma
// Skill -> sousSkill -> Technology

export const skills = [
  {
    id: "software-engineering",
    title: "Software Engineering",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "frontend",
        title: "Front-end",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "html",
            title: "HTML",
            icon: "https://img.icons8.com/?size=100&id=20909&format=png&color=000000",
            color: "#E34F26",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "css",
            title: "CSS",
            icon: "https://img.icons8.com/?size=100&id=21278&format=png&color=000000",
            color: "#1572B6",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "javascript",
            title: "JavaScript",
            icon: "https://img.icons8.com/?size=100&id=108784&format=png&color=000000",
            color: "#F7DF1E",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "typescript",
            title: "TypeScript",
            icon: "https://img.icons8.com/?size=100&id=uJM6fQYqDaZK&format=png&color=000000",
            color: "#3178C6",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "react",
            title: "React",
            icon: "https://img.icons8.com/?size=100&id=asWSSTBrDlTW&format=png&color=000000",
            color: "#61DAFB",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "vue",
            title: "Vue.js",
            icon: "https://img.icons8.com/?size=100&id=rY6agKizO9eb&format=png&color=000000",
            color: "#4FC08D",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "angular",
            title: "Angular",
            icon: "https://img.icons8.com/?size=100&id=71257&format=png&color=000000",
            color: "#DD0031",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "svelte",
            title: "Svelte",
            icon: "https://img.icons8.com/?size=100&id=Mm35TzLKahiF&format=png&color=000000",
            color: "#FF3E00",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "nextjs",
            title: "Next.js",
            icon: "https://img.icons8.com/?size=100&id=yUdJlcKanVbh&format=png&color=000000",
            color: "#000000",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "nuxtjs",
            title: "Nuxt.js",
            icon: "https://img.icons8.com/?size=100&id=nvrsJYs7j9Vb&format=png&color=000000",
            color: "#00DC82",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "gatsby",
            title: "Gatsby",
            icon: "https://img.icons8.com/?size=100&id=9ZCwMt6fg4MT&format=png&color=000000",
            color: "#663399",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "backend",
        title: "Back-end",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "nodejs",
            title: "Node.js",
            icon: "https://img.icons8.com/?size=100&id=54087&format=png&color=000000",
            color: "#339933",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "python",
            title: "Python",
            icon: "https://img.icons8.com/?size=100&id=13441&format=png&color=000000",
            color: "#3776AB",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "java",
            title: "Java",
            icon: "https://img.icons8.com/?size=100&id=Pd2x9GWu9ovX&format=png&color=000000",
            color: "#ED8B00",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "csharp",
            title: "C#",
            icon: "https://img.icons8.com/?size=100&id=45490&format=png&color=000000",
            color: "#239120",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "php",
            title: "PHP",
            icon: "https://img.icons8.com/?size=100&id=f0R4xVI4Sc8O&format=png&color=000000",
            color: "#777BB4",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "ruby",
            title: "Ruby",
            icon: "https://img.icons8.com/?size=100&id=22189&format=png&color=000000",
            color: "#CC342D",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "go",
            title: "Go",
            icon: "🐹",
            color: "#00ADD8",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "rust",
            title: "Rust",
            icon: "https://img.icons8.com/?size=100&id=AeV543ttZrcT&format=png&color=000000",
            color: "#000000",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "C",
            title: "C",
            icon: "https://img.icons8.com/?size=100&id=40670&format=png&color=000000",
            color: "#000000",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "C++",
            title: "C++",
            icon: "https://img.icons8.com/?size=100&id=TpULddJc4gTh&format=png&color=000000",
            color: "#000000",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "mobile",
        title: "Mobile Development",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "swift",
            title: "Swift",
            icon: "https://img.icons8.com/?size=100&id=XH8DlMsSOmWT&format=png&color=000000",
            color: "#FA7343",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "kotlin",
            title: "Kotlin",
            icon: "https://img.icons8.com/?size=100&id=ZoxjA0jZDdFZ&format=png&color=000000",
            color: "#0095D5",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "react-native",
            title: "React Native",
            icon: "https://img.icons8.com/?size=100&id=123603&format=png&color=000000",
            color: "#61DAFB",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "flutter",
            title: "Flutter",
            icon: "https://img.icons8.com/?size=100&id=7I3BjCqe9rjG&format=png&color=000000",
            color: "#02569B",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "devops",
        title: "DevOps & Infrastructure",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "docker",
            title: "Docker",
            icon: "https://img.icons8.com/?size=100&id=22813&format=png&color=000000",
            color: "#2496ED",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "kubernetes",
            title: "Kubernetes",
            icon: "https://img.icons8.com/?size=100&id=cvzmaEA4kC0o&format=png&color=000000",
            color: "#326CE5",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "jenkins",
            title: "Jenkins",
            icon: "https://img.icons8.com/?size=100&id=39292&format=png&color=000000",
            color: "#D33833",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "git",
            title: "Git",
            icon: "https://img.icons8.com/?size=100&id=20906&format=png&color=000000",
            color: "#F05032",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "github-actions",
            title: "GitHub Actions",
            icon: "https://img.icons8.com/?size=100&id=62856&format=png&color=000000",
            color: "#2088FF",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "terraform",
            title: "Terraform",
            icon: "https://img.icons8.com/?size=100&id=WncR8Bcg5nE9&format=png&color=000000",
            color: "#623CE4",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "ansible",
            title: "Ansible",
            icon: "https://img.icons8.com/?size=100&id=SJNUZD3A4el4&format=png&color=000000",
            color: "#EE0000",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "database",
    title: "Database & Storage",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "sql",
        title: "SQL Databases",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "mysql",
            title: "MySQL",
            icon: "https://img.icons8.com/?size=100&id=T3OGfb1OU0RD&format=png&color=000000",
            color: "#4479A1",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "postgresql",
            title: "PostgreSQL",
            icon: "https://img.icons8.com/?size=100&id=Pv4IGT0TSpt8&format=png&color=000000",
            color: "#336791",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "sqlite",
            title: "SQLite",
            icon: "https://img.icons8.com/?size=100&id=VMRAbKfEzssG&format=png&color=000000",
            color: "#003B57",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "oracle",
            title: "Oracle",
            icon: "https://img.icons8.com/?size=100&id=39913&format=png&color=000000",
            color: "#F80000",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "nosql",
        title: "NoSQL Databases",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "mongodb",
            title: "MongoDB",
            icon: "https://img.icons8.com/?size=100&id=tBBf3P8HL0vR&format=png&color=000000",
            color: "#47A248",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "redis",
            title: "Redis",
            icon: "https://img.icons8.com/?size=100&id=pHS3eRpynIRQ&format=png&color=000000",
            color: "#DC382D",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "cassandra",
            title: "Cassandra",
            icon: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Apache-cassandra-icon.png?20110626213050",
            color: "#1287B1",
            category: "database",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "orm",
        title: "ORM & Query Builders",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "prisma",
            title: "Prisma",
            icon: "https://img.icons8.com/?size=100&id=YKKmRFS8Utmm&format=png&color=000000",
            color: "#2D3748",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "typeorm",
            title: "TypeORM",
            icon: "🏗️",
            color: "#E83524",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "sequelize",
            title: "Sequelize",
            icon: "📊",
            color: "#52B0E7",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "data-science",
    title: "Data Science & Analytics",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "analytics",
        title: "Data Analytics",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "pandas",
            title: "Pandas",
            icon: "🐼",
            color: "#150458",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "numpy",
            title: "NumPy",
            icon: "https://img.icons8.com/?size=100&id=aR9CXyMagKIS&format=png&color=000000",
            color: "#013243",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "r",
            title: "R",
            icon: "📈",
            color: "#276DC3",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "sql",
            title: "SQL",
            icon: "https://img.icons8.com/?size=100&id=Ign0QG33bZzq&format=png&color=000000",
            color: "#336791",
            category: "language",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "visualization",
        title: "Data Visualization",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "tableau",
            title: "Tableau",
            icon: "📊",
            color: "#E97627",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "powerbi",
            title: "Power BI",
            icon: "https://img.icons8.com/?size=100&id=QMTbsd0FVhHS&format=png&color=000000",
            color: "#F2C811",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "matplotlib",
            title: "Matplotlib",
            icon: "https://img.icons8.com/?size=100&id=TkX1totjFmAD&format=png&color=000000",
            color: "#11557C",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "ai-ml",
    title: "AI & Machine Learning",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "frameworks",
        title: "ML Frameworks",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "tensorflow",
            title: "TensorFlow",
            icon: "https://img.icons8.com/?size=100&id=n3QRpDA7KZ7P&format=png&color=000000",
            color: "#FF6F00",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "pytorch",
            title: "PyTorch",
            icon: "https://img.icons8.com/?size=100&id=jH4BpkMnRrU5&format=png&color=000000",
            color: "#EE4C2C",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "scikit-learn",
            title: "Scikit-learn",
            icon: "https://img.icons8.com/?size=100&id=M4btD4MSsZNI&format=png&color=000000",
            color: "#F7931E",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "keras",
            title: "Keras",
            icon: "https://img.icons8.com/?size=100&id=z2pN6mJXIC4u&format=png&color=000000",
            color: "#D00000",
            category: "framework",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "nlp",
        title: "Natural Language Processing",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "huggingface",
            title: "Hugging Face",
            icon: "https://img.icons8.com/?size=100&id=sop9ROXku5bb&format=png&color=000000",
            color: "#FFD21E",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "openai",
            title: "OpenAI",
            icon: "https://img.icons8.com/?size=100&id=FBO05Dys9QCg&format=png&color=000000",
            color: "#412991",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "pentesting",
        title: "Penetration Testing",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "metasploit",
            title: "Metasploit",
            icon: "https://img.icons8.com/?size=100&id=97AFS4JiW8vx&format=png&color=000000",
            color: "#1976D2",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "nmap",
            title: "Nmap",
            icon: "https://img.icons8.com/?size=100&id=9b5wowKIlo9d&format=png&color=000000",
            color: "#4CAF50",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "wireshark",
            title: "Wireshark",
            icon: "https://img.icons8.com/?size=100&id=rOHcpTUtCTjr&format=png&color=000000",
            color: "#1976D2",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "burp-suite",
            title: "Burp Suite",
            icon: "https://img.icons8.com/?size=100&id=cVUr1WGmhrbq&format=png&color=000000",
            color: "#FF5722",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "network-security",
        title: "Network Security",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "snort",
            title: "Snort",
            icon: "🚨",
            color: "#E91E63",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "pfsense",
            title: "pfSense",
            icon: "🛡️",
            color: "#2196F3",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "cisco-asa",
            title: "Cisco ASA",
            icon: "🔒",
            color: "#1976D2",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "design",
    title: "UI/UX Design",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "design-tools",
        title: "Design Tools",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "figma",
            title: "Figma",
            icon: "https://img.icons8.com/?size=100&id=zfHRZ6i1Wg0U&format=png&color=000000",
            color: "#F24E1E",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "adobe-xd",
            title: "Adobe XD",
            icon: "https://icons8.com/icon/4VVL78edhbW9/adobe-xd",
            color: "#FF61F6",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "sketch",
            title: "Sketch",
            icon: "https://icons8.com/icon/9G868KxEhqEq/sketch",
            color: "#F7B500",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "photoshop",
            title: "Photoshop",
            icon: "https://img.icons8.com/?size=100&id=13677&format=png&color=000000",
            color: "#31A8FF",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "illustrator",
            title: "Illustrator",
            icon: "https://img.icons8.com/?size=100&id=13631&format=png&color=000000",
            color: "#FF9A00",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "prototyping",
        title: "Prototyping & Testing",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "invision",
            title: "InVision",
            icon: "https://img.icons8.com/?size=100&id=cRGU9_-pgw3i&format=png&color=000000",
            color: "#FF3366",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "maze",
            title: "Maze",
            icon: "https://img.icons8.com/?size=100&id=69209&format=png&color=000000",
            color: "#09CF83",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "principle",
            title: "Principle",
            icon: "⚡",
            color: "#5B57D9",
            category: "tool",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
  {
    id: "cloud",
    title: "Cloud & Infrastructure",
    createdAt: new Date(),
    updatedAt: new Date(),
    sousSkills: [
      {
        id: "aws",
        title: "Amazon Web Services",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "ec2",
            title: "EC2",
            icon: "https://img.icons8.com/?size=100&id=e6uRfPIDgoXi&format=png&color=000000",
            color: "#FF9900",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "s3",
            title: "S3",
            icon: "https://img.icons8.com/?size=100&id=106501&format=png&color=000000",
            color: "#569A31",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "lambda",
            title: "Lambda",
            icon: "https://img.icons8.com/?size=100&id=Y9Kxy8Xl1id8&format=png&color=000000",
            color: "#FF9900",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "rds",
            title: "RDS",
            icon: "🗄️",
            color: "#3F48CC",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "azure",
        title: "Microsoft Azure",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "azure-app-service",
            title: "App Service",
            icon: "https://img.icons8.com/?size=100&id=VLKafOkk3sBX&format=png&color=000000",
            color: "#0078D4",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "azure-functions",
            title: "Azure Functions",
            icon: "⚡",
            color: "#0078D4",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
      {
        id: "gcp",
        title: "Google Cloud Platform",
        createdAt: new Date(),
        updatedAt: new Date(),
        technologies: [
          {
            id: "gce",
            title: "Compute Engine",
            icon: "https://img.icons8.com/?size=100&id=20776&format=png&color=000000",
            color: "#4285F4",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "cloud-functions",
            title: "Cloud Functions",
            icon: "https://img.icons8.com/?size=100&id=3FDJsdSpK6cv&format=png&color=000000",
            color: "#4285F4",
            category: "platform",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
      },
    ],
  },
];
