export const countries = [
  {
    id: 1,
    name: "Aruba",
    flag: "AW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Afghanistan",
    flag: "AF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "Angola",
    flag: "AO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: "Anguilla",
    flag: "AI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: "France",
    flag: "FR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: "United States",
    flag: "US",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    name: "Germany",
    flag: "DE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    name: "United Kingdom",
    flag: "GB",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    name: "Albania",
    flag: "AL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    name: "Algeria",
    flag: "DZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    name: "American Samoa",
    flag: "AS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    name: "Andorra",
    flag: "AD",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    name: "Antarctica",
    flag: "AQ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    name: "Antigua and Barbuda",
    flag: "AG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    name: "Argentina",
    flag: "AR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    name: "Armenia",
    flag: "AM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    name: "Australia",
    flag: "AU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    name: "Austria",
    flag: "AT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    name: "Azerbaijan",
    flag: "AZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    name: "Bahamas",
    flag: "BS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    name: "Bahrain",
    flag: "BH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 22,
    name: "Bangladesh",
    flag: "BD",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 23,
    name: "Barbados",
    flag: "BB",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 24,
    name: "Belarus",
    flag: "BY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 25,
    name: "Belgium",
    flag: "BE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 26,
    name: "Belize",
    flag: "BZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 27,
    name: "Benin",
    flag: "BJ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 28,
    name: "Bermuda",
    flag: "BM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 29,
    name: "Bhutan",
    flag: "BT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 30,
    name: "Bolivia",
    flag: "BO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 31,
    name: "Bosnia and Herzegovina",
    flag: "BA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 32,
    name: "Botswana",
    flag: "BW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 33,
    name: "Brazil",
    flag: "BR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 34,
    name: "British Virgin Islands",
    flag: "VG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 35,
    name: "Brunei",
    flag: "BN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 36,
    name: "Bulgaria",
    flag: "BG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 37,
    name: "Burkina Faso",
    flag: "BF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 38,
    name: "Burundi",
    flag: "BI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 39,
    name: "Cambodia",
    flag: "KH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 40,
    name: "Cameroon",
    flag: "CM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 41,
    name: "Canada",
    flag: "CA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 42,
    name: "Cape Verde",
    flag: "CV",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 43,
    name: "Cayman Islands",
    flag: "KY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 44,
    name: "Central African Republic",
    flag: "CF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 45,
    name: "Chad",
    flag: "TD",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 46,
    name: "Chile",
    flag: "CL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 47,
    name: "China",
    flag: "CN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 48,
    name: "Christmas Island",
    flag: "CX",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 49,
    name: "Cocos Islands",
    flag: "CC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 50,
    name: "Colombia",
    flag: "CO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 51,
    name: "Comoros",
    flag: "KM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 52,
    name: "Congo",
    flag: "CG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 53,
    name: "Democratic Republic of Congo",
    flag: "CD",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 54,
    name: "Cook Islands",
    flag: "CK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 55,
    name: "Costa Rica",
    flag: "CR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 56,
    name: "Croatia",
    flag: "HR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 57,
    name: "Cuba",
    flag: "CU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 58,
    name: "Cyprus",
    flag: "CY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 59,
    name: "Czech Republic",
    flag: "CZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 60,
    name: "Denmark",
    flag: "DK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 61,
    name: "Djibouti",
    flag: "DJ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 62,
    name: "Dominica",
    flag: "DM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 63,
    name: "Dominican Republic",
    flag: "DO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 64,
    name: "Ecuador",
    flag: "EC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 65,
    name: "Egypt",
    flag: "EG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 66,
    name: "El Salvador",
    flag: "SV",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 67,
    name: "Equatorial Guinea",
    flag: "GQ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 68,
    name: "Eritrea",
    flag: "ER",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 69,
    name: "Estonia",
    flag: "EE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 70,
    name: "Ethiopia",
    flag: "ET",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 71,
    name: "Falkland Islands",
    flag: "FK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 72,
    name: "Faroe Islands",
    flag: "FO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 73,
    name: "Fiji",
    flag: "FJ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 74,
    name: "Finland",
    flag: "FI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 75,
    name: "French Guiana",
    flag: "GF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 76,
    name: "French Polynesia",
    flag: "PF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 77,
    name: "Gabon",
    flag: "GA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 78,
    name: "Gambia",
    flag: "GM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 79,
    name: "Georgia",
    flag: "GE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 80,
    name: "Ghana",
    flag: "GH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 81,
    name: "Gibraltar",
    flag: "GI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 82,
    name: "Greece",
    flag: "GR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 83,
    name: "Greenland",
    flag: "GL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 84,
    name: "Grenada",
    flag: "GD",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 85,
    name: "Guadeloupe",
    flag: "GP",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 86,
    name: "Guam",
    flag: "GU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 87,
    name: "Guatemala",
    flag: "GT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 88,
    name: "Guernsey",
    flag: "GG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 89,
    name: "Guinea",
    flag: "GN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 90,
    name: "Guinea-Bissau",
    flag: "GW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 91,
    name: "Guyana",
    flag: "GY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 92,
    name: "Haiti",
    flag: "HT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 93,
    name: "Honduras",
    flag: "HN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 94,
    name: "Hong Kong",
    flag: "HK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 95,
    name: "Hungary",
    flag: "HU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 96,
    name: "Iceland",
    flag: "IS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 97,
    name: "India",
    flag: "IN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 98,
    name: "Indonesia",
    flag: "ID",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 99,
    name: "Iran",
    flag: "IR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 100,
    name: "Iraq",
    flag: "IQ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 101,
    name: "Ireland",
    flag: "IE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 102,
    name: "Israel",
    flag: "IL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 103,
    name: "Italy",
    flag: "IT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 104,
    name: "Ivory Coast",
    flag: "CI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 105,
    name: "Jamaica",
    flag: "JM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 106,
    name: "Japan",
    flag: "JP",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 107,
    name: "Jersey",
    flag: "JE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 108,
    name: "Jordan",
    flag: "JO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 109,
    name: "Kazakhstan",
    flag: "KZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 110,
    name: "Kenya",
    flag: "KE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 111,
    name: "Kiribati",
    flag: "KI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 112,
    name: "North Korea",
    flag: "KP",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 113,
    name: "South Korea",
    flag: "KR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 114,
    name: "Kuwait",
    flag: "KW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 115,
    name: "Kyrgyzstan",
    flag: "KG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 116,
    name: "Laos",
    flag: "LA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 117,
    name: "Latvia",
    flag: "LV",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 118,
    name: "Lebanon",
    flag: "LB",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 119,
    name: "Lesotho",
    flag: "LS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 120,
    name: "Liberia",
    flag: "LR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 121,
    name: "Libya",
    flag: "LY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 122,
    name: "Liechtenstein",
    flag: "LI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 123,
    name: "Lithuania",
    flag: "LT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 124,
    name: "Luxembourg",
    flag: "LU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 125,
    name: "Macao",
    flag: "MO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 126,
    name: "North Macedonia",
    flag: "MK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 127,
    name: "Madagascar",
    flag: "MG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 128,
    name: "Malawi",
    flag: "MW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 129,
    name: "Malaysia",
    flag: "MY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 130,
    name: "Maldives",
    flag: "MV",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 131,
    name: "Mali",
    flag: "ML",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 132,
    name: "Malta",
    flag: "MT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 133,
    name: "Marshall Islands",
    flag: "MH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 134,
    name: "Martinique",
    flag: "MQ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 135,
    name: "Mauritania",
    flag: "MR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 136,
    name: "Mauritius",
    flag: "MU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 137,
    name: "Mayotte",
    flag: "YT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 138,
    name: "Mexico",
    flag: "MX",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 139,
    name: "Micronesia",
    flag: "FM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 140,
    name: "Moldova",
    flag: "MD",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 141,
    name: "Monaco",
    flag: "MC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 142,
    name: "Mongolia",
    flag: "MN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 143,
    name: "Montenegro",
    flag: "ME",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 144,
    name: "Montserrat",
    flag: "MS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 145,
    name: "Morocco",
    flag: "MA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 146,
    name: "Mozambique",
    flag: "MZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 147,
    name: "Myanmar",
    flag: "MM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 148,
    name: "Namibia",
    flag: "NA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 149,
    name: "Nauru",
    flag: "NR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 150,
    name: "Nepal",
    flag: "NP",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 151,
    name: "Netherlands",
    flag: "NL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 152,
    name: "New Caledonia",
    flag: "NC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 153,
    name: "New Zealand",
    flag: "NZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 154,
    name: "Nicaragua",
    flag: "NI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 155,
    name: "Niger",
    flag: "NE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 156,
    name: "Nigeria",
    flag: "NG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 157,
    name: "Niue",
    flag: "NU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 158,
    name: "Norfolk Island",
    flag: "NF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 159,
    name: "Northern Mariana Islands",
    flag: "MP",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 160,
    name: "Norway",
    flag: "NO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 161,
    name: "Oman",
    flag: "OM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 162,
    name: "Pakistan",
    flag: "PK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 163,
    name: "Palau",
    flag: "PW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 164,
    name: "Palestine",
    flag: "PS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 165,
    name: "Panama",
    flag: "PA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 166,
    name: "Papua New Guinea",
    flag: "PG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 167,
    name: "Paraguay",
    flag: "PY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 168,
    name: "Peru",
    flag: "PE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 169,
    name: "Philippines",
    flag: "PH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 170,
    name: "Pitcairn",
    flag: "PN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 171,
    name: "Poland",
    flag: "PL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 172,
    name: "Portugal",
    flag: "PT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 173,
    name: "Puerto Rico",
    flag: "PR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 174,
    name: "Qatar",
    flag: "QA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 175,
    name: "Réunion",
    flag: "RE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 176,
    name: "Romania",
    flag: "RO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 177,
    name: "Russia",
    flag: "RU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 178,
    name: "Rwanda",
    flag: "RW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 179,
    name: "Saint Barthélemy",
    flag: "BL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 180,
    name: "Saint Helena",
    flag: "SH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 181,
    name: "Saint Kitts and Nevis",
    flag: "KN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 182,
    name: "Saint Lucia",
    flag: "LC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 183,
    name: "Saint Martin",
    flag: "MF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 184,
    name: "Saint Pierre and Miquelon",
    flag: "PM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 185,
    name: "Saint Vincent and the Grenadines",
    flag: "VC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 186,
    name: "Samoa",
    flag: "WS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 187,
    name: "San Marino",
    flag: "SM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 188,
    name: "São Tomé and Príncipe",
    flag: "ST",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 189,
    name: "Saudi Arabia",
    flag: "SA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 190,
    name: "Senegal",
    flag: "SN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 191,
    name: "Serbia",
    flag: "RS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 192,
    name: "Seychelles",
    flag: "SC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 193,
    name: "Sierra Leone",
    flag: "SL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 194,
    name: "Singapore",
    flag: "SG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 195,
    name: "Sint Maarten",
    flag: "SX",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 196,
    name: "Slovakia",
    flag: "SK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 197,
    name: "Slovenia",
    flag: "SI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 198,
    name: "Solomon Islands",
    flag: "SB",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 199,
    name: "Somalia",
    flag: "SO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 200,
    name: "South Africa",
    flag: "ZA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 201,
    name: "South Georgia and the South Sandwich Islands",
    flag: "GS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 202,
    name: "South Korea",
    flag: "KR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 203,
    name: "South Sudan",
    flag: "SS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 204,
    name: "Spain",
    flag: "ES",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 205,
    name: "Sri Lanka",
    flag: "LK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 206,
    name: "Sudan",
    flag: "SD",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 207,
    name: "Suriname",
    flag: "SR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 208,
    name: "Svalbard and Jan Mayen",
    flag: "SJ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 209,
    name: "Swaziland",
    flag: "SZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 210,
    name: "Sweden",
    flag: "SE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 211,
    name: "Switzerland",
    flag: "CH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 212,
    name: "Syria",
    flag: "SY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 213,
    name: "Taiwan",
    flag: "TW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 214,
    name: "Tajikistan",
    flag: "TJ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 215,
    name: "Tanzania",
    flag: "TZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 216,
    name: "Thailand",
    flag: "TH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 217,
    name: "Timor-Leste",
    flag: "TL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 218,
    name: "Togo",
    flag: "TG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 219,
    name: "Tokelau",
    flag: "TK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 220,
    name: "Tonga",
    flag: "TO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 221,
    name: "Trinidad and Tobago",
    flag: "TT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 222,
    name: "Tunisia",
    flag: "TN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 223,
    name: "Turkey",
    flag: "TR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 224,
    name: "Turkmenistan",
    flag: "TM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 225,
    name: "Turks and Caicos Islands",
    flag: "TC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 226,
    name: "Tuvalu",
    flag: "TV",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 227,
    name: "Uganda",
    flag: "UG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 228,
    name: "Ukraine",
    flag: "UA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 229,
    name: "United Arab Emirates",
    flag: "AE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 230,
    name: "United Kingdom",
    flag: "GB",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 231,
    name: "United States",
    flag: "US",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 232,
    name: "United States Minor Outlying Islands",
    flag: "UM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 233,
    name: "Uruguay",
    flag: "UY",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 234,
    name: "Uzbekistan",
    flag: "UZ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 235,
    name: "Vanuatu",
    flag: "VU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 236,
    name: "Vatican City",
    flag: "VA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 237,
    name: "Venezuela",
    flag: "VE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 238,
    name: "Vietnam",
    flag: "VN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 239,
    name: "Virgin Islands (British)",
    flag: "VG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 240,
    name: "Virgin Islands (U.S.)",
    flag: "VI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 241,
    name: "Wallis and Futuna",
    flag: "WF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 242,
    name: "Western Sahara",
    flag: "EH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 243,
    name: "Yemen",
    flag: "YE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 244,
    name: "Zambia",
    flag: "ZM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 245,
    name: "Zimbabwe",
    flag: "ZW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 246,
    name: "Åland Islands",
    flag: "AX",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 247,
    name: "Antarctica",
    flag: "AQ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 248,
    name: "Bouvet Island",
    flag: "BV",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 249,
    name: "French Southern Territories",
    flag: "TF",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Utilisation avec ReactCountryFlag dans un composant .tsx :
// <ReactCountryFlag flag={country.flag} svg />
